// The Purge
// by HDTeam
// Fun Server
// [0] remoteExec ["ht_Purge_fnc_Purge"];
0 fadesound 0; 
5 fadeSound 1;
playSound "purge";
hintsilent parsetext"<t color='#940000' size='1.5'>!ACHTUNG! Die Purge</t><br/><br/><t size='1.3'>Starte jetzt (Sie lauft 15 Minuten)</t>";
uisleep 60;
uisleep 60;
hintsilent parsetext"<t color='#940000' size='1.5'>!ACHTUNG! Die Purge</t><br/><br/><t size='1.3'>Läuft noch 14 Minuten</t>";
playsound "alarm";
uisleep 60;
hintsilent parsetext"<t color='#940000' size='1.5'>!ACHTUNG! Die Purge</t><br/><br/><t size='1.3'>Läuft noch 13 Minuten</t>";
playsound "alarm";
uisleep 60;
hintsilent parsetext"<t color='#940000' size='1.5'>!ACHTUNG! Die Purge</t><br/><br/><t size='1.3'>Läuft noch 12 Minuten</t>";
playsound "alarm";
uisleep 60;
hintsilent parsetext"<t color='#940000' size='1.5'>!ACHTUNG! Die Purge</t><br/><br/><t size='1.3'>Läuft noch 11 Minuten</t>";
playsound "alarm";
uisleep 60;
hintsilent parsetext"<t color='#940000' size='1.5'>!ACHTUNG! Die Purge</t><br/><br/><t size='1.3'>Läuft noch 10 Minuten</t>";
playsound "alarm";
uisleep 60;
hintsilent parsetext"<t color='#940000' size='1.5'>!ACHTUNG! Die Purge</t><br/><br/><t size='1.3'>Läuft noch 9 Minuten</t>";
playsound "alarm";
uisleep 60;
hintsilent parsetext"<t color='#940000' size='1.5'>!ACHTUNG! Die Purge</t><br/><br/><t size='1.3'>Läuft noch 8 Minuten</t>";
playsound "alarm";
uisleep 60;
hintsilent parsetext"<t color='#940000' size='1.5'>!ACHTUNG! Die Purge</t><br/><br/><t size='1.3'>Läuft noch 7 Minuten</t>";
playsound "alarm";
uisleep 60;
hintsilent parsetext"<t color='#940000' size='1.5'>!ACHTUNG! Die Purge</t><br/><br/><t size='1.3'>Läuft noch 6 Minuten</t>";
playsound "alarm";
uisleep 60;
hintsilent parsetext"<t color='#940000' size='1.5'>!ACHTUNG! Die Purge</t><br/><br/><t size='1.3'>Läuft noch 5 Minuten</t>";
playsound "alarm";
uisleep 60;
hintsilent parsetext"<t color='#940000' size='1.5'>!ACHTUNG! Die Purge</t><br/><br/><t size='1.3'>Läuft noch 4 Minuten</t>";
playsound "alarm";
uisleep 60;
hintsilent parsetext"<t color='#940000' size='1.5'>!ACHTUNG! Die Purge</t><br/><br/><t size='1.3'>Läuft noch 3 Minuten</t>";
playsound "alarm";
uisleep 60;
hintsilent parsetext"<t color='#940000' size='1.5'>!ACHTUNG! Die Purge</t><br/><br/><t size='1.3'>Läuft noch 2 Minuten</t>";
playsound "alarm";
uisleep 60;
hintsilent parsetext"<t color='#940000' size='1.5'>!ACHTUNG! Die Purge</t><br/><br/><t size='1.3'>Läuft noch 1 Minuten</t>";
playsound "alarm";
uisleep 50;
0 fadesound 0; 
5 fadeSound 1;
hintsilent parsetext"<t color='#940000' size='1.5'>!ACHTUNG!</t><br/><br/><t size='1.3'>Die Purge Endet in</t>";
uisleep 5;
hintsilent parsetext"<t color='#ff6600' size='1.5'>!ACHTUNG!</t><br/><br/><t color='#ff0000' size='2'>3</t>";
playsound "alarm";
uisleep 1;
hintsilent parsetext"<t color='#ff6600' size='1.5'>!ACHTUNG!</t><br/><br/><t color='#ff0000' size='2'>2</t>";
playsound "alarm";
uisleep 1;
hintsilent parsetext"<t color='#ff6600' size='1.5'>!ACHTUNG!</t><br/><br/><t color='#ff0000' size='2'>1</t>";
playSound "Bye";
cutText ["und jetzt?","Black OUT"];
uisleep 0.5;
[] Spawn {
setDate [0,0,0,12,0];
60 setwaves 1;
60 setfog 100.99;
60 setRain 1;
60 setOvercast 1;
60 setRainbow 1;
60 setWaves 1;
60 setLightnings 1;
forceWeatherChange;
};
uisleep 6;
cutText ["","Black in"];
hintsilent parsetext"<t color='#ff6600' size='1.5'>!ACHTUNG! Die Purge</t><br/><br/><t size='2'>ist zu Ende Danke fürs mitmachen</t>";
uisleep 20;
cutText ["","Black OUT"]; 
uisleep 0.5; 
cutText ["","Black IN"];
uisleep 0.5;
cutText ["","Black OUT"];
uisleep 1; 
[] Spawn {
setDate [0,0,0,12,0];
60 setwaves 0;
60 setfog 0.00;
60 setRain 0;
60 setOvercast 0;
60 setRainbow 0;
60 setWaves 0;
60 setLightnings 0;
forceWeatherChange;
};
uisleep 3;
cutText ["","Black IN"];
uisleep 0.5;
cutText ["","Black OUT"]; 
uisleep 0.5; 
cutText ["","Black IN"];
uisleep 0.5; 
cutText ["","Black OUT"]; 
uisleep 0.5; 
cutText ["","Black IN"];